import { env } from 'cloudflare:workers';
import { emptyState, type State } from '@/lib/model';
import { hasSession, sameOrigin, unauthorized } from '@/lib/auth';
export const runtime='edge';
type Config={SUPABASE_URL?:string;SUPABASE_PUBLISHABLE_KEY?:string;SUPABASE_APP_TOKEN?:string};
type Row={revision:number;data:State};
const unavailable=(message='No se pudo acceder a Supabase. Tus cambios no se guardaron; inténtalo de nuevo.')=>Response.json({error:message},{status:503});
function config(){const c=env as unknown as Config;if(!c.SUPABASE_URL||!c.SUPABASE_PUBLISHABLE_KEY||!c.SUPABASE_APP_TOKEN)throw new Error('Falta la configuración de Supabase');return c as Required<Config>}
function url(c:Required<Config>,query:string){return `${c.SUPABASE_URL}/rest/v1/cuentas_claras_state?${query}`}
function headers(c:Required<Config>,extra:Record<string,string>={}){return {'apikey':c.SUPABASE_PUBLISHABLE_KEY,'x-cuentas-token':c.SUPABASE_APP_TOKEN,'Content-Type':'application/json',...extra}}
async function read(c:Required<Config>):Promise<Row|null>{const r=await fetch(url(c,'select=revision,data&id=eq.1'),{headers:headers(c),cache:'no-store'});if(!r.ok)throw new Error(`Supabase devolvió ${r.status} al leer`);const rows=await r.json() as Row[];return rows[0]||null}
export async function GET(request:Request){try{if(!await hasSession(request))return unauthorized();const c=config();let row=await read(c);if(!row){const initial=emptyState();const r=await fetch(url(c,''),{method:'POST',headers:headers(c,{'Prefer':'return=representation'}),body:JSON.stringify({id:1,revision:initial.revision,data:initial})});if(!r.ok&&r.status!==409)throw new Error(`Supabase devolvió ${r.status} al iniciar`);row=await read(c)}if(!row)throw new Error('No se encontró el registro después de iniciar');return Response.json({...row.data,revision:row.revision})}catch(e){console.error(e);return unavailable()}}
export async function PUT(request:Request){try{if(!await hasSession(request))return unauthorized();if(!sameOrigin(request))return new Response(null,{status:403});const c=config();const next=await request.json() as State;if(!next||!Array.isArray(next.entries)||!Array.isArray(next.audit)||!Number.isInteger(next.revision))return Response.json({error:'Datos inválidos'},{status:400});const revision=next.revision+1;const r=await fetch(url(c,`id=eq.1&revision=eq.${next.revision}&select=revision`),{method:'PATCH',headers:headers(c,{'Prefer':'return=representation'}),body:JSON.stringify({revision,data:{...next,revision},updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(`Supabase devolvió ${r.status} al guardar`);const rows=await r.json() as {revision:number}[];if(!rows.length)return Response.json({error:'Los datos cambiaron en otra ventana. Recarga para revisar antes de guardar.'},{status:409});return Response.json({revision:rows[0].revision})}catch(e){console.error(e);return unavailable()}}
