import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {mergeStates} from '../android-web/merge.ts';
const cacheKey='grafiplot-offline-v1',grantKey='grafiplot-offline-grant';
const state=()=>({revision:1,settings:{currency:'PEN'},entries:[],shifts:[],workers:[],attendance:[],yape:[],sources:[],audit:[],demo:false});
function harness(store=new Map<string,string>()){
 const identity={sub:'owner',session_id:'session'};let online=true,cloud=state(),auth=true,fail=false,writeFail=false,diskFail=false;
 const remote=async(path:string,init:any={})=>{if(fail)return Response.json({error:'unavailable'},{status:503});if(path==='/api/auth')return Response.json({authenticated:auth});if(init.method==='PUT'){if(writeFail)return Response.json({error:'race'},{status:409});const next=JSON.parse(init.body);cloud={...next,revision:next.revision+1};return Response.json({revision:cloud.revision})}return Response.json(cloud)};
 const output:any={};const js=ts.transpileModule(readFileSync(new URL('../android-web/offline.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 runInNewContext(js,{exports:output,require:(name:string)=>name==='./api'?{remoteFetch:remote,sessionIdentity:async()=>identity}:name==='./merge'?{mergeStates}:{native:true,storage:{get:async(k:string)=>store.get(k)||null,set:async(k:string,v:string)=>{if(diskFail)throw new Error('disk');store.set(k,v)},remove:async(k:string)=>store.delete(k)}},Response,Date,Promise,JSON,Error,CustomEvent:class{},Event:class{},window:{dispatchEvent:()=>{}},navigator:{get onLine(){return online}}});
 return {api:output,store,identity,setOnline:(v:boolean)=>online=v,setFail:(v:boolean)=>fail=v,setDiskFail:(v:boolean)=>diskFail=v,setWriteFail:(v:boolean)=>writeFail=v,setAuth:(v:boolean)=>auth=v,getCloud:()=>cloud,setCloud:(v:any)=>cloud=v};
}
async function initialized(){const h=harness();await h.api.apiFetch('/api/auth');await h.api.apiFetch('/api/state');return h}
test('primer acceso offline requiere validación previa',async()=>{const h=harness();h.setOnline(false);assert.equal((await h.api.apiFetch('/api/auth')).status,503);assert.equal((await h.api.apiFetch('/api/state')).status,401)});
test('guarda offline y recupera los datos después de reiniciar la lógica',async()=>{const h=await initialized();h.setOnline(false);const next=state();next.entries.push({id:'local',amount:10} as never);const r=await h.api.apiFetch('/api/state',{method:'PUT',body:JSON.stringify(next)});assert.equal(r.status,200);assert.equal((await r.json()).local,true);assert.equal(JSON.parse(h.store.get(cacheKey)!).pending,true);const restarted=harness(h.store);restarted.setOnline(false);assert.equal((await (await restarted.api.apiFetch('/api/auth')).json()).authenticated,true);assert.equal((await (await restarted.api.apiFetch('/api/state')).json()).entries[0].amount,10)});
test('sincroniza el documento una sola vez y conserva revisión del servidor',async()=>{const h=await initialized();const next=state();next.entries.push({id:'local',amount:10} as never);await h.api.apiFetch('/api/state',{method:'PUT',body:JSON.stringify(next)});await h.api.syncNow();await h.api.syncNow();assert.equal(h.getCloud().entries.length,1);assert.equal(h.getCloud().revision,2);assert.equal(JSON.parse(h.store.get(cacheKey)!).pending,false)});
test('caída de red permite acceso ya validado sin borrar la sesión local',async()=>{const h=await initialized();h.setFail(true);const r=await h.api.apiFetch('/api/auth');assert.equal((await r.json()).authenticated,true);assert.ok(h.store.get(grantKey))});
test('revocación bloquea acceso pero preserva cambios pendientes cifrados',async()=>{const h=await initialized();await h.api.apiFetch('/api/state',{method:'PUT',body:JSON.stringify(state())});h.setAuth(false);await h.api.apiFetch('/api/auth');assert.equal((await h.api.apiFetch('/api/state')).status,401);assert.equal(JSON.parse(h.store.get(cacheKey)!).pending,true)});
test('vencimiento del permiso offline obliga a reconectar',async()=>{const h=await initialized();const g=JSON.parse(h.store.get(grantKey)!);g.until=0;h.store.set(grantKey,JSON.stringify(g));h.setOnline(false);assert.equal((await h.api.apiFetch('/api/state')).status,401)});
test('no confirma un guardado si el almacenamiento falla',async()=>{const h=await initialized();h.setDiskFail(true);await assert.rejects(h.api.apiFetch('/api/state',{method:'PUT',body:JSON.stringify(state())}),/disk/);assert.equal(JSON.parse(h.store.get(cacheKey)!).pending,false)});
test('conflicto de revisión mantiene pendientes y no escribe la nube',async()=>{const h=await initialized();await h.api.apiFetch('/api/state',{method:'PUT',body:JSON.stringify(state())});h.setWriteFail(true);await assert.rejects(h.api.syncNow(),/Otro dispositivo/);assert.equal(JSON.parse(h.store.get(cacheKey)!).pending,true);assert.equal(h.getCloud().revision,1)});
test('cerrar sesión no elimina cambios pendientes',async()=>{const h=await initialized();await h.api.apiFetch('/api/state',{method:'PUT',body:JSON.stringify(state())});assert.equal((await h.api.apiFetch('/api/auth',{method:'DELETE'})).status,409);assert.ok(h.store.get(cacheKey))});
