import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {apiFetch} from '../api';
import {todayLima} from '../../lib/model';
import './style.css';
const url='https://gyvztqpvgtinxoqhyfbw.supabase.co/rest/v1/rpc/grafiplot_worker_';
const key='sb_publishable_m5tDCWoaiu-xP-lezwd3Lg_rlUfq118';
const deviceKey='grafiplot-worker-phone';
const draftKey='grafiplot-worker-draft';
type Worker={id:string;name:string};
type Device={token:string;workers:Worker[]};
type Expense={concept:string;amount:number;method:string};
type Report={date:string;shift:number;workerId:string;opening:number;cashSales:number;counted:number;hours:number;note:string;expenses:Expense[]};
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
function read<T>(k:string):T|null {try{return JSON.parse(localStorage.getItem(k)||'null') as T|null}catch{return null}}
const blank=():Report=>({date:todayLima(),shift:1,workerId:'',opening:0,cashSales:0,counted:0,hours:7,note:'',expenses:[]});
async function rpc(name:string,body:object,token?:string){const r=await fetch(url+name,{method:'POST',headers:{apikey:key,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message||'No se pudo enviar. Revisa tu conexión e intenta nuevamente.');return j}
function App(){
 const admin=new URLSearchParams(location.search).get('activar')==='1';
 const [device,setDevice]=useState(()=>read<Device>(deviceKey));
 const [code,setCode]=useState(''),[invite,setInvite]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [report,setReport]=useState<Report>(()=>read<Report>(draftKey)||blank());
 const [review,setReview]=useState(false);
 function update(next:Report){setReport(next);localStorage.setItem(draftKey,JSON.stringify(next));setReview(false);setMessage('')}
 async function activate(){setBusy(true);setError('');try{const secret=code.trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(secret))throw new Error('Pega el código de activación que te dio tu encargado.');let token=localStorage.getItem('grafiplot-pending-token');if(!token){token=random();localStorage.setItem('grafiplot-pending-token',token)}const j=await rpc('activate',{p_invite:secret,p_token:token}) as {workers:Worker[]};const next={token,workers:j.workers};localStorage.setItem(deviceKey,JSON.stringify(next));localStorage.removeItem('grafiplot-pending-token');setDevice(next);setCode('');update({...report,workerId:j.workers[0]?.id||''});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function makeInvite(){setBusy(true);setError('');try{const r=await apiFetch('/api/auth');const j=await r.json();if(!r.ok||!j.authenticated)throw new Error('Primero entra al sistema principal con tu cuenta en este navegador.');const s=read<{access_token:string}>('grafiplot-pages-session');if(!s)throw new Error('Inicia sesión en el sistema principal.');const secret=random();await rpc('invite',{p_secret:secret},s.access_token);setInvite(secret)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function send(){if(!device)return;setBusy(true);setError('');try{const j=await rpc('submit',{p_token:device.token,p_report:report});setMessage('Informe recibido. Comprobante: '+j.id);setReview(false);localStorage.removeItem(draftKey);setReport({...blank(),workerId:report.workerId,shift:report.shift});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const worker=device?.workers.find(w=>w.id===report.workerId);
 const expected=Math.round((report.opening+report.cashSales-report.expenses.filter(e=>e.method==='efectivo').reduce((n,e)=>n+e.amount,0))*100)/100;
 return <main><header><span className="brand">grafiplot<span>●</span></span><h1>Mi informe diario</h1><p>Un envío por trabajador, fecha y turno.</p></header>{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}<p>Ya quedó guardado en el sistema.</p></div>}
 {admin?<section><h2>Autorizar el único celular</h2><p>Entra al <a href="./index.html" target="_blank" rel="noreferrer">sistema principal</a> con tu cuenta en este navegador. Luego genera el código y pégalo una sola vez en la APK.</p><p>Generar otro código retira inmediatamente el acceso del celular anterior.</p><button onClick={()=>void makeInvite()} disabled={busy}>Generar código de activación</button>{invite&&<><label>Código válido durante 7 días<textarea readOnly value={invite}/></label><button className="secondary" onClick={()=>void navigator.clipboard.writeText(invite).then(()=>setMessage('Código copiado')).catch(()=>setError('Selecciona y copia el código.'))}>Copiar código</button></>}</section>:!device?<section><h2>Activar este celular</h2><p>Tu encargado te dará un código. Solo se usa una vez y autoriza este celular para enviar informes.</p><label>Código de activación<textarea value={code} onChange={e=>setCode(e.target.value)} autoCapitalize="none" autoComplete="off" spellCheck={false}/></label><button disabled={busy} onClick={()=>void activate()}>{busy?'Activando…':'Activar celular'}</button></section>:<form onSubmit={e=>{e.preventDefault();setError('');setReview(true)}}><section><label>Trabajador<select required value={report.workerId} onChange={e=>update({...report,workerId:e.target.value})}><option value="" disabled>Elige tu nombre</option>{device.workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><div className="date">Hoy · {todayLima()}</div>{report.date!==todayLima()&&<p className="error">Hay un borrador de otro día. <button type="button" onClick={()=>update({...blank(),workerId:report.workerId})}>Empezar informe de hoy</button></p>}<label>Turno<select value={report.shift} onChange={e=>update({...report,shift:Number(e.target.value)})}><option value={1}>Mañana</option><option value={2}>Tarde</option></select></label></section>
 <section><h2>Caja del turno · S/</h2>{([['opening','Efectivo al empezar'],['cashSales','Ventas en efectivo'],['counted','Efectivo contado al terminar']] as const).map(([k,label])=><label key={k}>{label}<input required type="number" inputMode="decimal" min="0" max="1000000" step="0.01" value={report[k]} onChange={e=>update({...report,[k]:Number(e.target.value)})}/></label>)}</section>
 <section><h2>Gastos del turno</h2>{report.expenses.map((x,i)=><div className="expense" key={i}><label>Concepto<input required maxLength={160} value={x.concept} onChange={e=>update({...report,expenses:report.expenses.map((v,n)=>n===i?{...v,concept:e.target.value}:v)})}/></label><label>Importe (S/)<input required type="number" inputMode="decimal" min="0.01" max="1000000" step="0.01" value={x.amount} onChange={e=>update({...report,expenses:report.expenses.map((v,n)=>n===i?{...v,amount:Number(e.target.value)}:v)})}/></label><button className="secondary" type="button" onClick={()=>update({...report,expenses:report.expenses.filter((_,n)=>n!==i)})}>Quitar del borrador</button></div>)}<button className="secondary" type="button" disabled={report.expenses.length>=20} onClick={()=>update({...report,expenses:[...report.expenses,{concept:'',amount:0,method:'efectivo'}]})}>+ Agregar gasto</button></section>
 <section><label>Horas trabajadas<input required type="number" min="0" max="16" step="0.25" value={report.hours} onChange={e=>update({...report,hours:Number(e.target.value)})}/></label><p>Efectivo esperado con este informe: <b>S/ {expected.toFixed(2)}</b></p><label>Observaciones {expected!==report.counted&&'(explica la diferencia de caja)'}<textarea required={expected!==report.counted} maxLength={1000} value={report.note} onChange={e=>update({...report,note:e.target.value})}/></label></section>
 {review?<section className="review"><h2>Revisa antes de enviar</h2><p>{worker?.name} · {report.date} · {report.shift===1?'Mañana':'Tarde'}</p><p>Ventas efectivo: S/ {report.cashSales.toFixed(2)}<br/>Efectivo contado: S/ {report.counted.toFixed(2)}<br/>Gastos: {report.expenses.length}</p><p>Después de enviarlo no podrás cambiarlo.</p><button type="button" disabled={busy} onClick={()=>void send()}>{busy?'Enviando…':'Confirmar y enviar informe'}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setReview(false)}>Volver al borrador</button></section>:<button disabled={busy||report.date!==todayLima()}>Revisar informe</button>}
 </form>}<footer>Solo envío de informes · Se necesita conexión a internet.</footer></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
