import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {apiFetch} from '../api';
import {todayLima} from '../../lib/model';
import './style.css';
const url='https://gyvztqpvgtinxoqhyfbw.supabase.co/rest/v1/rpc/grafiplot_worker_';
const key='sb_publishable_m5tDCWoaiu-xP-lezwd3Lg_rlUfq118';
const deviceKey='grafiplot-worker-phone';
const draftKey='grafiplot-worker-count-draft';
type Device={token:string};
type Draft={date:string;shift:number;counted:string};
const blank=():Draft=>({date:todayLima(),shift:1,counted:''});
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
function read<T>(k:string):T|null {try{return JSON.parse(localStorage.getItem(k)||'null') as T|null}catch{return null}}
async function rpc(name:string,body:object,token?:string){const r=await fetch(url+name,{method:'POST',headers:{apikey:key,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message||'No se pudo enviar. Revisa tu conexión e intenta nuevamente.');return j}
function App(){
 const admin=new URLSearchParams(location.search).get('activar')==='1';
 const [device,setDevice]=useState(()=>read<Device>(deviceKey));
 const [code,setCode]=useState(''),[invite,setInvite]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [report,setReport]=useState<Draft>(()=>read<Draft>(draftKey)||blank());
 const [review,setReview]=useState(false);
 function update(next:Draft){setReport(next);localStorage.setItem(draftKey,JSON.stringify(next));setReview(false);setMessage('')}
 async function activate(){setBusy(true);setError('');try{const secret=code.trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(secret))throw new Error('Pega el código de activación que te dio tu encargado.');let token=localStorage.getItem('grafiplot-pending-token');if(!token){token=random();localStorage.setItem('grafiplot-pending-token',token)}await rpc('activate',{p_invite:secret,p_token:token});const next={token};localStorage.setItem(deviceKey,JSON.stringify(next));localStorage.removeItem('grafiplot-pending-token');setDevice(next);setCode('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function makeInvite(){setBusy(true);setError('');try{const r=await apiFetch('/api/auth');const j=await r.json();if(!r.ok||!j.authenticated)throw new Error('Primero entra al sistema principal con tu cuenta en este navegador.');const s=read<{access_token:string}>('grafiplot-pages-session');if(!s)throw new Error('Inicia sesión en el sistema principal.');const secret=random();await rpc('invite',{p_secret:secret},s.access_token);setInvite(secret);setMessage('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function send(){if(!device)return;setBusy(true);setError('');try{const counted=Number(report.counted);if(report.counted.trim()===''||!Number.isFinite(counted)||counted<0||counted>1000000)throw new Error('Escribe el efectivo contado al cierre.');const j=await rpc('submit',{p_token:device.token,p_report:{date:report.date,shift:report.shift,counted}});setMessage('Conteo recibido. Comprobante: '+j.id);setReview(false);localStorage.removeItem(draftKey);setReport({...blank(),shift:report.shift});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main><header><span className="brand">grafiplot<span>●</span></span><h1>Efectivo al cierre</h1><p>Cuenta el efectivo de tu turno y envíalo.</p></header>{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}{!admin&&<p>Ya quedó guardado en el sistema.</p>}</div>}
 {admin?<section><h2>Autorizar el único celular</h2><p>Entra al <a href="./index.html" target="_blank" rel="noreferrer">sistema principal</a> con tu cuenta en este navegador. Luego genera el código y pégalo una sola vez en la APK.</p><p>Generar otro código retira inmediatamente el acceso del celular anterior.</p><button onClick={()=>void makeInvite()} disabled={busy}>Generar código de activación</button>{invite&&<><label>Código válido durante 7 días<textarea readOnly value={invite}/></label><button className="secondary" onClick={()=>void navigator.clipboard.writeText(invite).then(()=>setMessage('Código copiado')).catch(()=>setError('Selecciona y copia el código.'))}>Copiar código</button></>}</section>:!device?<section><h2>Activar este celular</h2><p>Tu encargado te dará un código. Solo se usa una vez.</p><label>Código de activación<textarea value={code} onChange={e=>setCode(e.target.value)} autoCapitalize="none" autoComplete="off" spellCheck={false}/></label><button disabled={busy} onClick={()=>void activate()}>{busy?'Activando…':'Activar celular'}</button></section>:<form onSubmit={e=>{e.preventDefault();setError('');setReview(true)}}>
 <section><div className="date">Hoy · {todayLima()}</div>{report.date!==todayLima()&&<p className="error">Este borrador es de otro día. <button type="button" onClick={()=>update(blank())}>Empezar conteo de hoy</button></p>}<label>Turno<select value={report.shift} onChange={e=>update({...report,shift:Number(e.target.value)})}><option value={1}>Mañana</option><option value={2}>Tarde</option></select></label><div className="cash-base"><span>Efectivo inicial automático</span><strong>S/ 60.00</strong></div><label className="closing-label">Ingrese el monto total que hay en efectivo en la caja<input className="closing-input" autoComplete="off" required type="number" inputMode="decimal" min="0" max="1000000" step="0.01" placeholder="0.00" value={report.counted} onChange={e=>update({...report,counted:e.target.value})}/></label><p className="help">Escribe todo el efectivo que hay en caja, incluidos los S/ 60 iniciales.</p></section>
 {review?<section className="review"><h2>Confirma el conteo</h2><p>{report.date} · {report.shift===1?'Mañana':'Tarde'}</p><strong className="review-amount">S/ {Number(report.counted).toFixed(2)}</strong><p>Después de enviarlo, solo el encargado podrá corregirlo.</p><button type="button" disabled={busy} onClick={()=>void send()}>{busy?'Enviando…':'Confirmar y enviar conteo'}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setReview(false)}>Volver al borrador</button></section>:<button disabled={busy||report.date!==todayLima()}>Revisar conteo</button>}
 </form>}<footer>Un conteo por turno · Se necesita internet.</footer></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
